name: wirless
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  jiffy: ^6.2.1
  intl: ^0.18.0
  http: ^0.13.6
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  show_up_animation: ^2.0.0
  auto_animated: ^3.2.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  flutter_local_notifications: ^15.1.1
  sqflite: ^2.3.0
  shared_preferences: ^2.2.1
  path: ^1.8.3
  qr_flutter: ^4.1.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.14
  dropdown_search: ^5.0.6
  badges: ^3.1.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  dartz: ^0.10.1
  fluttericon: ^2.0.0
  image_pickers: ^2.0.4+2
  google_sign_in: ^6.1.5
  responsive_builder: ^0.7.0
  device_preview: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  lottie: ^2.6.0
  firebase_messaging: ^14.7.1
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  flutter_rating_bar: ^4.0.1
  flutter_image_slideshow: ^0.1.6
  rename: ^3.0.1
  plugin_platform_interface: ^2.0.2
  flutter_ringtone_player: ^3.2.0
  flutter_credit_card: ^4.0.1
  dio: ^5.3.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  rating_dialog: ^2.0.4
  flutter_tawkto: ^0.0.2
  webview_flutter: ^3.0.4
  flutter_paypal_payment: ^1.0.6
  flutter_stripe: ^9.4.0


dev_dependencies:
  flutter_native_splash: ^2.3.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#040424"
  image: assest\img\395389130_373066381715388_2150827379726798829_n-modified.png
  android: true
  ios: true
  android_gravity: center

flutter:
      
  uses-material-design: true
  assets:
    - assest/img/
    - assest/img/man/
    - assest/lootis/

  fonts:
    - family: Myfont1
      fonts:
        - asset: assest/fonts/Arabic/Cairo-Light.ttf
        - asset: assest/fonts/Arabic/Cairo-Bold.ttf
